    .text
    .align 2

    .globl fafft_rvv_encode
    .type fafft_rvv_encode, @function
fafft_rvv_encode:
    /*
     * Dummy placeholder only.
     * TODO: implement RVV encode_to_gft.
     */
    ret

    .size fafft_rvv_encode, .-fafft_rvv_encode


    .globl fafft_rvv_decode
    .type fafft_rvv_decode, @function
fafft_rvv_decode:
    /*
     * Dummy placeholder only.
     * TODO: implement RVV decode_from_gft.
     */
    ret

    .size fafft_rvv_decode, .-fafft_rvv_decode